### ISSUE TITLE
[Question] warnings when opening files

### ISSUE THREAD

**Issue by scheung38** [ballerina-guides/messaging-with-kafka#35]
**Description:**
Errors after git clone, opened in VSCode IDE and getting 
![Screenshot 2021-01-01 at 23 27 29](https://user-images.githubusercontent.com/1273014/103447881-2f233880-4c89-11eb-9f0d-121d0d8e53cc.png)
![Screenshot 2021-01-01 at 23 27 22](https://user-images.githubusercontent.com/1273014/103447882-30546580-4c89-11eb-9492-6f0b169f098e.png)
![Screenshot 2021-01-01 at 23 26 55](https://user-images.githubusercontent.com/1273014/103447883-30ecfc00-4c89-11eb-8d59-c26305dd595a.png)

**OS, DB, other environment details and versions:**    
Mac OSX VSCode

> ballerina version            
jBallerina 1.2.6
Language specification 2020R1
Compatible JRE 8 not found. Please follow the instructions in <BALLERINA_HOME>/INSTALL.txt to install and setup Ballerina.

**Steps to reproduce:**
git clone project
opened in VSCode

How to resolve these warnings/errors?

**Comment by nadeeshaan** [comment]
@scheung38 Can you check whether you have set `ballerina.home ` property in VSCode settings? Also, please share a the vscode plugin startup log to check whether the language server has picked a wrong version as follows

<img width="1356" alt="Screenshot 2021-01-04 at 07 54 42" src="https://user-images.githubusercontent.com/1329674/103495903-4a956b80-4e62-11eb-9331-2ea2430f6843.png">

**Comment by ThisaruGuruge** [comment]
This guide seems to be out of date. Please check the [Ballerina By Examples](https://ballerina.io/learn/by-example/) for the updated examples.

Following are two of the examples we have for Kafka

* [Consumer](https://ballerina.io/learn/by-example/kafka-consumer-service.html)
* [Producer](https://ballerina.io/learn/by-example/kafka-producer.html)
